### ISSUE TITLE
Minification issue

### ISSUE THREAD

**Issue by blackotruck** [michaelahlers/angular-timezones#13]
Greetings!... i've been using this great module on a project without any problems, until i minified the app. I'm using $filter('tzAlign') but this gives 

```
Error: [$injector:unpr] Unknown provider: aProvider <- a <- tzAlignFilter
```

The weird thing is that i inspected the minified js and the tzAlign filter is declared. Other filters like uppercase are working fine. I guess that ultimately i could use the unminified version of the module, at least no mangled, but i'm trying to reduce the load time of the app. So, what other solution may be?

**Comment by michaelahlers** [comment]
Hey @blackotruck, I'm no longer maintaining this project (time constraints, and I'm actively moving away from Angular). However, I do have a recommendation.

See [line 160](https://github.com/michaelahlers/angular-timezones/blob/64bfb75e2022393b87e1017f704fca7fa93f3edf/js/angular-timezones.js#L160) of [`angular-timezones.js`](https://github.com/michaelahlers/angular-timezones/blob/64bfb75e2022393b87e1017f704fca7fa93f3edf/js/angular-timezones.js) that reads:

``` javascript
module.filter('tzAlign', function ($timezones) {
  /* ... */
})
```

Your minification might be rewriting variable `$timezones`, which uses Angular's clever function signature reading to determine which injections to perform. After either copying this script into your project, or forking on GitHub and changing your Bower dependencies, try varying this to [make explicit the dependencies](https://docs.angularjs.org/guide/di) for `tzAlign` as follows:

``` javascript
module.filter('tzAlign', ['$timezones', function ($timezones) {
  /* ... */
}])
```

That _should_ become impervious to any mangling minifiers typically perform. And please let me know how this works out for you!

**Comment by blackotruck** [comment]
Wow! thanks, that worked great, and i new it was something like that, but i didn't checked the js file, as all other 3rd parties use the array notation i assumed you used too. Again, thanks for the quick response.

**Comment by michaelahlers** [comment]
You're welcome, and I'm glad to help!
