### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by mrzasa** [michaelahlers/angular-timezones#7]
I would like to use angular-timezones in my project, but I don't want to do a code theft. Could you add a license file or just  a license info so that we know how could we use that library?

**Comment by michaelahlers** [comment]
You got it (with 95c0d23). Apologies for the oversight!

**Comment by michaelahlers** [comment]
Quick FYI: I'll be fixing that build error soon, and bringing in some updates in the near future. (Been too busy for much side-project maintenance.)

**Comment by mrzasa** [comment]
:+1:  thanks a lot.
