### ISSUE TITLE
Replace full path in Bower dependencies with version only

### ISSUE THREAD

**Issue by yguerro** [michaelahlers/angular-timezones#9]
With [bower](https://github.com/bower/bower), installation is failing on Windows because of a full path being hard-coded in the list of dependencies:

The following:

``` json
{
  "dependencies" : {
    ...
    "timezone-js" : "git@github.com:mde/timezone-js.git#v0.4.4"
  }
}
```

should be replaced by something like (as other dependencies):

``` json
{
  "dependencies" : {
    ...
    "timezone-js" : "0.4.4"
  }
}
```

Testing locally it works like a charm.

**Comment by michaelahlers** [comment]
Deprecating this project. Please either fork this project, or file the issue with any active forks.
